build:
    environment:
        php:
            version: 5.6.0
    tests:
        override:
            -
                command: vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.xml
                coverage:
                    file: coverage.xml
                    format: php-clover
