language: php

sudo: false

cache:
    directories:
      - $HOME/.composer/cache

before_script:
    - composer install

script: vendor/bin/phpunit -c phpunit.xml.dist

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: hhvm